package Hibernate;
// Generated 5 juin 2018 16:17:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Activite generated by hbm2java
 */
public class Activite  implements java.io.Serializable {


     private long idactivite;
     private Professeur professeur;
     private Salle salle;
     private String type;
     private String matiere;
     private Set suivres = new HashSet(0);

    public Activite() {
    }

	
    public Activite(long idactivite, Professeur professeur, Salle salle, String type, String matiere) {
        this.idactivite = idactivite;
        this.professeur = professeur;
        this.salle = salle;
        this.type = type;
        this.matiere = matiere;
    }
    public Activite(long idactivite, Professeur professeur, Salle salle, String type, String matiere, Set suivres) {
       this.idactivite = idactivite;
       this.professeur = professeur;
       this.salle = salle;
       this.type = type;
       this.matiere = matiere;
       this.suivres = suivres;
    }
   
    public long getIdactivite() {
        return this.idactivite;
    }
    
    public void setIdactivite(long idactivite) {
        this.idactivite = idactivite;
    }
    public Professeur getProfesseur() {
        return this.professeur;
    }
    
    public void setProfesseur(Professeur professeur) {
        this.professeur = professeur;
    }
    public Salle getSalle() {
        return this.salle;
    }
    
    public void setSalle(Salle salle) {
        this.salle = salle;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getMatiere() {
        return this.matiere;
    }
    
    public void setMatiere(String matiere) {
        this.matiere = matiere;
    }
    public Set getSuivres() {
        return this.suivres;
    }
    
    public void setSuivres(Set suivres) {
        this.suivres = suivres;
    }




}


