package Hibernate;
// Generated 5 juin 2018 16:17:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant  implements java.io.Serializable {


     private long idetudiant;
     private String nom;
     private String prenom;
     private String adressepostal;
     private long groupe;
     private Set informations = new HashSet(0);
     private Set suivres = new HashSet(0);

    public Etudiant() {
    }

	
    public Etudiant(long idetudiant, String nom, String prenom, String adressepostal, long groupe) {
        this.idetudiant = idetudiant;
        this.nom = nom;
        this.prenom = prenom;
        this.adressepostal = adressepostal;
        this.groupe = groupe;
    }
    public Etudiant(long idetudiant, String nom, String prenom, String adressepostal, long groupe, Set informations, Set suivres) {
       this.idetudiant = idetudiant;
       this.nom = nom;
       this.prenom = prenom;
       this.adressepostal = adressepostal;
       this.groupe = groupe;
       this.informations = informations;
       this.suivres = suivres;
    }
   
    public long getIdetudiant() {
        return this.idetudiant;
    }
    
    public void setIdetudiant(long idetudiant) {
        this.idetudiant = idetudiant;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdressepostal() {
        return this.adressepostal;
    }
    
    public void setAdressepostal(String adressepostal) {
        this.adressepostal = adressepostal;
    }
    public long getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(long groupe) {
        this.groupe = groupe;
    }
    public Set getInformations() {
        return this.informations;
    }
    
    public void setInformations(Set informations) {
        this.informations = informations;
    }
    public Set getSuivres() {
        return this.suivres;
    }
    
    public void setSuivres(Set suivres) {
        this.suivres = suivres;
    }




}


