package Hibernate;
// Generated 5 juin 2018 16:17:00 by Hibernate Tools 4.3.1



/**
 * Information generated by hbm2java
 */
public class Information  implements java.io.Serializable {


     private long idinformation;
     private Etudiant etudiant;
     private Professeur professeur;
     private Type type;
     private String valeur;

    public Information() {
    }

	
    public Information(long idinformation, Type type, String valeur) {
        this.idinformation = idinformation;
        this.type = type;
        this.valeur = valeur;
    }
    public Information(long idinformation, Etudiant etudiant, Professeur professeur, Type type, String valeur) {
       this.idinformation = idinformation;
       this.etudiant = etudiant;
       this.professeur = professeur;
       this.type = type;
       this.valeur = valeur;
    }
   
    public long getIdinformation() {
        return this.idinformation;
    }
    
    public void setIdinformation(long idinformation) {
        this.idinformation = idinformation;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    public Professeur getProfesseur() {
        return this.professeur;
    }
    
    public void setProfesseur(Professeur professeur) {
        this.professeur = professeur;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public String getValeur() {
        return this.valeur;
    }
    
    public void setValeur(String valeur) {
        this.valeur = valeur;
    }




}


