package Hibernate;
// Generated 5 juin 2018 16:17:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Professeur generated by hbm2java
 */
public class Professeur  implements java.io.Serializable {


     private long idprofesseur;
     private String nom;
     private String prenom;
     private String adressepostal;
     private Set informations = new HashSet(0);
     private Set activites = new HashSet(0);

    public Professeur() {
    }

	
    public Professeur(long idprofesseur, String nom, String prenom, String adressepostal) {
        this.idprofesseur = idprofesseur;
        this.nom = nom;
        this.prenom = prenom;
        this.adressepostal = adressepostal;
    }
    public Professeur(long idprofesseur, String nom, String prenom, String adressepostal, Set informations, Set activites) {
       this.idprofesseur = idprofesseur;
       this.nom = nom;
       this.prenom = prenom;
       this.adressepostal = adressepostal;
       this.informations = informations;
       this.activites = activites;
    }
   
    public long getIdprofesseur() {
        return this.idprofesseur;
    }
    
    public void setIdprofesseur(long idprofesseur) {
        this.idprofesseur = idprofesseur;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdressepostal() {
        return this.adressepostal;
    }
    
    public void setAdressepostal(String adressepostal) {
        this.adressepostal = adressepostal;
    }
    public Set getInformations() {
        return this.informations;
    }
    
    public void setInformations(Set informations) {
        this.informations = informations;
    }
    public Set getActivites() {
        return this.activites;
    }
    
    public void setActivites(Set activites) {
        this.activites = activites;
    }




}


