package Hibernate;
// Generated 5 juin 2018 16:17:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salle generated by hbm2java
 */
public class Salle  implements java.io.Serializable {


     private long idsalle;
     private long numero;
     private String type;
     private Set activites = new HashSet(0);

    public Salle() {
    }

	
    public Salle(long idsalle, long numero, String type) {
        this.idsalle = idsalle;
        this.numero = numero;
        this.type = type;
    }
    public Salle(long idsalle, long numero, String type, Set activites) {
       this.idsalle = idsalle;
       this.numero = numero;
       this.type = type;
       this.activites = activites;
    }
   
    public long getIdsalle() {
        return this.idsalle;
    }
    
    public void setIdsalle(long idsalle) {
        this.idsalle = idsalle;
    }
    public long getNumero() {
        return this.numero;
    }
    
    public void setNumero(long numero) {
        this.numero = numero;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getActivites() {
        return this.activites;
    }
    
    public void setActivites(Set activites) {
        this.activites = activites;
    }




}


