package Hibernate;
// Generated 5 juin 2018 16:17:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Suivre generated by hbm2java
 */
public class Suivre  implements java.io.Serializable {


     private long idsuivre;
     private Activite activite;
     private Etudiant etudiant;
     private String statut;
     private double note;
     private Date temps;
     private String appreciation;

    public Suivre() {
    }

	
    public Suivre(long idsuivre, Activite activite, Etudiant etudiant, String statut, double note, Date temps) {
        this.idsuivre = idsuivre;
        this.activite = activite;
        this.etudiant = etudiant;
        this.statut = statut;
        this.note = note;
        this.temps = temps;
    }
    public Suivre(long idsuivre, Activite activite, Etudiant etudiant, String statut, double note, Date temps, String appreciation) {
       this.idsuivre = idsuivre;
       this.activite = activite;
       this.etudiant = etudiant;
       this.statut = statut;
       this.note = note;
       this.temps = temps;
       this.appreciation = appreciation;
    }
   
    public long getIdsuivre() {
        return this.idsuivre;
    }
    
    public void setIdsuivre(long idsuivre) {
        this.idsuivre = idsuivre;
    }
    public Activite getActivite() {
        return this.activite;
    }
    
    public void setActivite(Activite activite) {
        this.activite = activite;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }
    public double getNote() {
        return this.note;
    }
    
    public void setNote(double note) {
        this.note = note;
    }
    public Date getTemps() {
        return this.temps;
    }
    
    public void setTemps(Date temps) {
        this.temps = temps;
    }
    public String getAppreciation() {
        return this.appreciation;
    }
    
    public void setAppreciation(String appreciation) {
        this.appreciation = appreciation;
    }




}


