package Hibernate;
// Generated 5 juin 2018 16:17:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private long idtype;
     private String nom;
     private Set informations = new HashSet(0);

    public Type() {
    }

	
    public Type(long idtype, String nom) {
        this.idtype = idtype;
        this.nom = nom;
    }
    public Type(long idtype, String nom, Set informations) {
       this.idtype = idtype;
       this.nom = nom;
       this.informations = informations;
    }
   
    public long getIdtype() {
        return this.idtype;
    }
    
    public void setIdtype(long idtype) {
        this.idtype = idtype;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getInformations() {
        return this.informations;
    }
    
    public void setInformations(Set informations) {
        this.informations = informations;
    }




}


