DROP TABLE etudiant;
DROP TABLE professeur;
DROP TABLE salle;
DROP TABLE activite;
DROP TABLE suivre;
DROP TABLE type;
DROP TABLE information;

CREATE TABLE etudiant (
  idEtudiant number(11) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom varchar(20) NOT NULL,
  prenom varchar(20) NOT NULL,
  adressePostal varchar(100) NOT NULL,
  groupe number(11) NOT NULL,
  PRIMARY KEY (idEtudiant)
);

CREATE TABLE professeur (
  idProfesseur number(11) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom varchar(20) NOT NULL,
  prenom varchar(20) NOT NULL,
  adressePostal varchar(100) NOT NULL,
  PRIMARY KEY (idProfesseur)
);

CREATE TABLE salle (
  idSalle number(11) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  numero number(11) NOT NULL,
  type varchar(20) NOT NULL,
  PRIMARY KEY (idSalle)
);

CREATE TABLE activite (
  idActivite number(11) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  type varchar(20) NOT NULL,
  matiere varchar(20) NOT NULL,
  idProfesseur number(11) NOT NULL,
  idSalle number(11) NOT NULL,
  PRIMARY KEY (idActivite),
  FOREIGN KEY (idProfesseur) REFERENCES professeur(idProfesseur),
  FOREIGN KEY (idSalle) REFERENCES salle(idSalle)
);

CREATE TABLE suivre (
  idSuivre number(11) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  statut varchar(20) NOT NULL,
  note float NOT NULL,
  temps DATE NOT NULL,
  appreciation varchar2(200),
  idEtudiant number(11) NOT NULL,
  idActivite number(11) NOT NULL,
  PRIMARY KEY (idSuivre),
  FOREIGN KEY (idEtudiant) REFERENCES etudiant(idEtudiant),
  FOREIGN KEY (idActivite) REFERENCES activite(idActivite)
);

CREATE TABLE type (
  idType number(11) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom varchar(100) NOT NULL,
  PRIMARY KEY (idType)
);

CREATE TABLE information (
  idInformation number(11) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  valeur varchar2(100) NOT NULL,
  idType number(11) NOT NULL,
  idEtudiant number(11),
  idProfesseur number(11),
  PRIMARY KEY (idInformation),
  FOREIGN KEY (idType) REFERENCES type(idType),
  FOREIGN KEY (idEtudiant) REFERENCES etudiant(idEtudiant),
  FOREIGN KEY (idProfesseur) REFERENCES professeur(idProfesseur)
);

CREATE INDEX index_information_type ON information(idType);
CREATE INDEX index_information_professeur ON information(idProfesseur);
CREATE INDEX index_information_etudiant ON information(idEtudiant);

CREATE INDEX index_suivre_etudiant ON suivre(idEtudiant);
CREATE INDEX index_suivre_activite ON suivre(idActivite);

CREATE INDEX index_activite_professeur ON activite(idProfesseur);
CREATE INDEX index_activite_salle ON activite(idSalle);

CREATE INDEX index_etudiant_groupe ON etudiant(groupe);
CREATE INDEX index_suivre_note ON suivre(note);
CREATE INDEX index_activite_matiere ON activite(matiere);
CREATE INDEX index_salle_type ON salle(type);

INSERT INTO etudiant
(nom, prenom, adressePostal, groupe)
VALUES
('Le Bohémien', 'Tintin', '28 rue de la Gitanerie', 2);



